# Generated by Django 5.0.2 on 2024-04-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to_author',
            field=models.TextField(null=True),
        ),
    ]
