# Generated by Django 4.2.11 on 2024-04-16 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_swaprequest_swapoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapoffer',
            name='offer_chore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_offers_related', to='posts.chore'),
        ),
    ]
