# Generated by Django 5.0.2 on 2024-04-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_reply_to_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply_to_author',
            new_name='reply_to_auth',
        ),
    ]
