# Generated by Django 4.2.11 on 2024-04-21 23:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_alter_swapoffer_offer_chore'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='assignees_completed',
            field=models.ManyToManyField(blank=True, related_name='completed_chores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chore',
            name='num_assignees_completed',
            field=models.IntegerField(default=0),
        ),
    ]
