# Generated by Django 4.2.11 on 2024-04-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_bill_num_payers_paid_bill_paid_bill_payers_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='paid',
        ),
    ]
