# Generated by Django 5.0.2 on 2024-03-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='group_icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
